version: '3.4'

services:

  eaasy:
    container_name: eaasy
    build:
      context: ./eaasy
      dockerfile: Dockerfile-dev
    volumes:
      - './eaasy:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.config.DevelopmentConfig
